"""empty message

Revision ID: 7f380dc7de83
Revises: 5f4c4025e26b
Create Date: 2019-04-13 08:25:03.958652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f380dc7de83'
down_revision = '5f4c4025e26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('start', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'start')
    # ### end Alembic commands ###
