"""empty message

Revision ID: 814c308a85ba
Revises: 7f380dc7de83
Create Date: 2019-04-13 08:57:33.293710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814c308a85ba'
down_revision = '7f380dc7de83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('genre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'genre')
    # ### end Alembic commands ###
